version: 2
jobs:
  feat2dev_plan:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      WKSPC: "d020"
    steps:
      - checkout
      - run:
          name: export aws creds
          command: |
            chmod +x .circleci/export_aws.sh
            .circleci/export_aws.sh
      - run: 
          name: version
          command: |
            terraform version
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: lint-validate
          command: |
            chmod +x .circleci/lint.sh
            chmod +x .circleci/validate.sh
            .circleci/lint.sh
            .circleci/validate.sh
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC || terraform workspace new $WKSPC
      - run: terraform plan -var-file=env/${WKSPC}.tfvars -var mysql_rds_password=$mysql_rds_password -var account_id=$aws_acc_id -input=false
  dev_plan:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      WKSPC: "d020"
    steps:
      - checkout
      - run:
          name: export aws creds
          command: |
            chmod +x .circleci/export_aws.sh
            .circleci/export_aws.sh
      - run: 
          name: version
          command: |
            terraform version
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: lint-validate
          command: |
            chmod +x .circleci/lint.sh
            chmod +x .circleci/validate.sh
            .circleci/lint.sh
            .circleci/validate.sh
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC || terraform workspace new $WKSPC
      - run: terraform plan -var-file=env/${WKSPC}.tfvars -var mysql_rds_password=$mysql_rds_password -var account_id=$aws_acc_id -input=false -out=plans/tfm.plan
      - persist_to_workspace:
          root: plans
          paths:
            - tfm.plan
  dev_apply:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      WKSPC: "d020"
    steps:
      - checkout
      - run:
          name: export aws creds
          command: |
            chmod +x .circleci/export_aws.sh
            .circleci/export_aws.sh
      - run: 
          name: version
          command: |
            terraform version
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC || terraform workspace new $WKSPC
      - attach_workspace:
          at: plans
      - run: terraform apply -input=false -auto-approve plans/tfm.plan
  dev2uat_plan:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      WKSPC: "t030"
    steps:
      - checkout
      - run:
          name: export aws creds
          command: |
            chmod +x .circleci/export_aws.sh
            .circleci/export_aws.sh
      - run: 
          name: version
          command: |
            terraform version
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: lint-validate
          command: |
            chmod +x .circleci/lint.sh
            chmod +x .circleci/validate.sh
            .circleci/lint.sh
            .circleci/validate.sh
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC || terraform workspace new $WKSPC
      - run: terraform plan -var-file=env/${WKSPC}.tfvars -var mysql_rds_password=$mysql_rds_password -var account_id=$aws_acc_id -input=false -out=plans/tfm.plan
  uat_plan:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      WKSPC: "t030"
    steps:
      - checkout
      - run:
          name: export aws creds
          command: |
            chmod +x .circleci/export_aws.sh
            .circleci/export_aws.sh
      - run: 
          name: version
          command: |
            terraform version
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: lint-validate
          command: |
            chmod +x .circleci/lint.sh
            chmod +x .circleci/validate.sh
            .circleci/lint.sh
            .circleci/validate.sh
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC || terraform workspace new $WKSPC
      - run: terraform plan -var-file=env/${WKSPC}.tfvars -var mysql_rds_password=$mysql_rds_password -var account_id=$aws_acc_id -input=false -out=plans/tfm.plan
      - persist_to_workspace:
          root: plans
          paths:
            - tfm.plan
  uat_apply:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      WKSPC: "t030"
    steps:
      - checkout
      - run:
          name: export aws creds
          command: |
            chmod +x .circleci/export_aws.sh
            .circleci/export_aws.sh
      - run: 
          name: version
          command: |
            terraform version
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC || terraform workspace new $WKSPC
      - attach_workspace:
          at: plans
      - run: terraform apply -input=false -auto-approve plans/tfm.plan
  uat2prd_plan:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      WKSPC: "p040"
    steps:
      - checkout
      - run:
          name: export aws creds
          command: |
            chmod +x .circleci/export_aws.sh
            .circleci/export_aws.sh
      - run: 
          name: version
          command: |
            terraform version
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: lint-validate
          command: |
            chmod +x .circleci/lint.sh
            chmod +x .circleci/validate.sh
            .circleci/lint.sh
            .circleci/validate.sh
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC || terraform workspace new $WKSPC
      - run: terraform plan -var-file=env/${WKSPC}.tfvars -var-file=env/${WKSPC}.tfvars -var account_id=$aws_acc_id -input=false -out=plans/tfm.plan
  prd_plan:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      WKSPC: "p040"
    steps:
      - checkout
      - run:
          name: export aws creds
          command: |
            chmod +x .circleci/export_aws.sh
            .circleci/export_aws.sh
      - run: 
          name: version
          command: |
            terraform version
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: lint-validate
          command: |
            chmod +x .circleci/lint.sh
            chmod +x .circleci/validate.sh
            .circleci/lint.sh
            .circleci/validate.sh
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC || terraform workspace new $WKSPC
      - run: terraform plan -var-file=env/${WKSPC}.tfvars -var account_id=$aws_acc_id -input=false -out=plans/tfm.plan
      - persist_to_workspace:
          root: plans
          paths:
            - tfm.plan
  prd_apply:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      WKSPC: "p040"
    steps:
      - checkout
      - run:
          name: export aws creds
          command: |
            chmod +x .circleci/export_aws.sh
            .circleci/export_aws.sh
      - run: 
          name: version
          command: |
            terraform version
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC || terraform workspace new $WKSPC      
      - attach_workspace:
          at: plans
      - run: terraform apply -input=false -auto-approve plans/tfm.plan
workflows:
  version: 2
  feat2dev:
    jobs:
      - feat2dev_plan:
          context: terraform
          filters:
            branches:
              ignore: 
                - master
                - uat
                - dev    
      - dev_plan:
          context: terraform
          filters: 
            branches:
              only: dev
              ignore: 
                - master
                - uat   
      - dev_apply:
          requires: 
            - dev_plan
          context: terraform
          filters: 
            branches:
              only: dev
              ignore: 
                - master
                - uat
 
  dev2uat:
    jobs:
      - dev2uat_plan:
          context: terraform
          filters:
            branches:
              only: dev  
              ignore: 
                - master
                - uat
                
      - uat_plan:
          context: terraform
          filters:
            branches:
              only: uat   
              ignore: 
                - master
                - dev         
      - uat_apply:
          requires: 
            - uat_plan
          context: terraform
          filters:
            branches:
              only: uat
              ignore: 
                - master
                - dev  
  uat2prd:
    jobs:
    - uat2prd_plan:
        context: terraform
        filters:
          branches:
            only: uat
            ignore: 
              - master
              - dev
    - prd_plan:
        context: terraform
        filters:
          branches:
            only: master
            ignore: 
              - uat
              - dev
    - prd_hold:
        type: approval
        requires:
          - prd_plan
        context: terraform
        filters:
          branches:
            only: master
            ignore: 
              - uat
              - dev
    - prd_apply:
        requires: 
          - prd_hold
        context: terraform
        filters:
          branches:
            only: master
            ignore: 
              - uat
              - dev